services:
  - type: web
    name: currency-api
    env: node
    rootDir: server
    buildCommand: npm ci && npm run build
    startCommand: node dist/server.js
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FREECURRENCYAPI_KEY
        sync: false
      - key: CORS_ORIGIN
        value: http://localhost:4200
